### PR TITLE
fix(linking): added timeout to linking process

### LINKED ISSUE #4933: Add timeout to 'linking satellites'
Add a timeout to linking satellites that kicks the user back to the sign in page after 30 seconds with an error message on the sign in page that says something like 'We were unable to log you in, please try again soon or create a new account.

Also investigate root cause of issue, Sheldon and Drew are debugging

### PR DESCRIPTION
**Pull request by ThomBos**
### What this PR does 📖
- 

### Which issue(s) this PR fixes 🔨
- Resolve #4933

### CODE REVIEW

File: pages/auth/unlock/index.vue [hunk 1]
```diff
@@ -107,6 +107,10 @@ ${this.$t('pages.unlock.choose_pin_description_2')}`
      * @example
      */
     async decrypt(redirect = true) {
+      const timeout = setTimeout(() => {
+        this.pin = ''
+        this.error = `${this.$t('errors.timeout')}`
+      }, 30000)
```
Comment (WanderingHogan) [inline pages/auth/unlock/index.vue:113]: very minor, can you add the timeout time to config.ts

**Review by WanderingHogan — CHANGES_REQUESTED** [review]

File: pages/auth/unlock/index.vue [hunk 2]
```diff
@@ -107,6 +107,10 @@ ${this.$t('pages.unlock.choose_pin_description_2')}`
      * @example
      */
     async decrypt(redirect = true) {
+      const timeout = setTimeout(() => {
+        this.pin = ''
+        this.error = `${this.$t('errors.timeout')}`
```
Comment (josephmcg) [inline pages/auth/unlock/index.vue:112]: no need to wrap with template literals if it's pure js

**Review by WanderingHogan — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]
